# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Liaison Integration Test'
    subscriptionId: '10ada5ed-74b4-4a28-a048-050f6e9973b7'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'LiaisonIntegrationServicesTest'
    location: 'UK South'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/aishaikram/StdLAPipeline/main/ArmStdLogicApp/template.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/aishaikram/StdLAPipeline/main/ArmStdLogicApp/parameters.json'
    overrideParameters: '-name Arm-Arm-AIStdLogApp -hostingPlanName ASP-ArmAIStdLogApp -storageAccountName aistdlogappstorage'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployStdLAPipelineTemplate'